version: '3.3'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - my-postgres-volume:/var/lib/postgresql/data

volumes:
  my-postgres-volume:

# prisma:
#   image: prismagraphql/prisma:latest
#   command: ["--host", "db", "--port", "5432", "--schema", "prisma/schema.prisma"]
#   ports:
#     - "4466:4466"
#   depends_on:
#     - db

