version: '3.3'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - my-postgres-volume:/var/lib/postgresql/data

volumes:
  my-postgres-volume:

