import { getServerSession } from "next-auth";
import get_user_by_email from "@/src/lib/get_user_by_email";
import { redirect } from "next/navigation";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();
  if (!session) redirect("/login");


  

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
